add admin API endpoints to set specfic scenario states
emundo/wiremock pull request #1
Opened 2021-12-01 12:42 UTC by willKo

Adds two endpoints to the admin api:
- GET /__admin/scenario/state?stateName=somestate
- POST /__admin/scenario/state
  With JsonBody-Attributes scenarioName and scenarioState scenarioState

2021-12-01 14:33 UTC, TabeaSpahn requested changes

2021-12-01 14:33 UTC, TabeaSpahn commented on docs-v2/_docs/stateful-behaviour.md
> +in Java, or posting an request with JsonBody (see below) to `http://<host>:<port>/__admin/scenario/state`.
warum hier eine neue zeile mitten im Satz?

2021-12-01 14:33 UTC, TabeaSpahn commented on docs-v2/_docs/stateful-behaviour.md
> +Java, or sending a HTTP.GET request to `http://<host>:<port>/__admin/scenario/state?scenarioName=name`.
auch hier, warum neue Zeile mitten im Satz, gibt es ein Regel für max line length im readme?

2021-12-01 14:33 UTC, TabeaSpahn commented on docs-v2/_docs/stateful-behaviour.md
> +The state of a specific scenario can be set to a specific state.
"set" ist hier falsch du redest ja in der Überschrift bon "getting".
Eher: "The state of a specific scenario can be retrieved at any time"
oder: "The state of a specific scenario can be gotten at any time"

2021-12-01 14:33 UTC, TabeaSpahn commented on src/main/java/com/github/tomakehurst/wiremock/admin/model/ScenarioStateParam.java
> + * Copyright (C) 2021 Thomas Akehurst
hast du das alle kopiert? Licensen sind nicht mein spzial gebiet. aber wenn das kopiert ist müsste man dann icht erwähnen, as es kopiert wurde und von wo?

2021-12-01 14:33 UTC, TabeaSpahn commented on src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
> +    WireMockResponse resetToFinalStateResponse =
vorher testen das der state nicht final ist?

2021-12-01 14:33 UTC, TabeaSpahn commented on src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java
> +    return new ResponseDefinition(HTTP_NOT_FOUND, body.getBytes());
Was ist der zewiter parameter und warum ist er nicht "null" wie bei den anderen ResponseDefinition(1 drüber und drunter)

2021-12-01 14:33 UTC, TabeaSpahn commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +              "scenarioName is not present, contains more than one value or the value is empty"));
müsste man hier auch noch überprüfen ob der state in dem scenario existiert?

2021-12-01 14:47 UTC, willKo commented on docs-v2/_docs/stateful-behaviour.md
> +Java, or sending a HTTP.GET request to `http://<host>:<port>/__admin/scenario/state?scenarioName=name`.
Gute frage, ich passe es mal an, und schaue mal was der spotless formatter damit macht

2021-12-01 14:51 UTC, willKo commented on src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
> +    WireMockResponse resetToFinalStateResponse =
Wiremock State ist initial immer "Started", bzw. "Scenario.STARTED" (http://wiremock.org/docs/stateful-behaviour/).
Und die Stubs wurden gerade erst definiert.

2021-12-01 14:54 UTC, willKo commented on src/main/java/com/github/tomakehurst/wiremock/admin/model/ScenarioStateParam.java
> + * Copyright (C) 2021 Thomas Akehurst
Habe nur den Licence Text kopiert (aus einem anderen File), alle files haben den selben copyright owner ( wiremock project owner) drin, da ich es eig. gemergt haben will dachte ich, ich lasse das mal so.

2021-12-01 14:56 UTC, willKo commented on src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java
> +    return new ResponseDefinition(HTTP_NOT_FOUND, body.getBytes());
Ist der Body des HTTP Requests für 404 (in dem Fall, wie es genutzt wird, der Name des "scenarios", welches nicht gefunden wurde.

2021-12-01 15:00 UTC, willKo commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +              "scenarioName is not present, contains more than one value or the value is empty"));
Ich denke nicht, später wird überprüft, ob das Szenario exisiert, sonst 404. 
Wenn das Szenario existiert, hat es auch einen State ( denke nicht, das der State null oder "" sein kann, wenn das szenario existiert, nicht getestet, selbst wenn das geht sollte es keinen Fehler bei der Ausführung hier geben (denke ich)).

2021-12-02 07:54 UTC, TabeaSpahn commented on src/main/java/com/github/tomakehurst/wiremock/admin/model/ScenarioStateParam.java
> + * Copyright (C) 2021 Thomas Akehurst
mhm, okay. finde ich etwas merkwürdig. aber wie gesagt bin da auch kein experte für.

2021-12-02 07:56 UTC, TabeaSpahn commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +              "scenarioName is not present, contains more than one value or the value is empty"));
okay falsch ausgedrückt.
sollte man nicht überprüfen, ob z.b beim request "test/final" der state "final" im szenario "test" existiert"?
oder passiert das wo anders und ich habe es übersehen?

2021-12-02 08:05 UTC, willKo commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +              "scenarioName is not present, contains more than one value or the value is empty"));
Ne, das passiert nicht. Aber dazu müsste ich erstmal wissen, welche States es alles gibt (ich prüfe mal, ob das einfach geht). 
Aber ansonsten wäre die Konsequenz, das bei dem Abruf kein Szenario gefunden wird, welches passen würde :-) 
-> kein Fehler, sondern, korrekt, da es dann keinen Endpoint für das Szenario gibt.

2021-12-02 08:18 UTC, willKo commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +              "scenarioName is not present, contains more than one value or the value is empty"));
Ok, fixed

2021-12-02 08:29 UTC, willKo commented on src/main/java/com/github/tomakehurst/wiremock/admin/model/ScenarioStateParam.java
> + * Copyright (C) 2021 Thomas Akehurst
Habe mal meinen Namen bei den Files, die ich erstellt habe, können die dann gerne ändern oder an meinem MR anprangern, so sollte es rechtlich besser passen ^^.

2021-12-02 09:17 UTC, SergejT34 commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +        || scenarioNameQueryParameter.firstValue() == "") {
.equals(""")

2021-12-02 09:40 UTC, SergejT34 commented on src/main/resources/swagger/wiremock-admin-api.json
> +          "200": {"description": "Successfull"},
```suggestion
          "200": {"description": "Successful"},
```

2021-12-02 09:40 UTC, SergejT34 commented on src/main/resources/swagger/wiremock-admin-api.json
> +          "200": {"description": "Successfull"},
```suggestion
          "200": {"description": "Successful"},
```

2021-12-02 09:44 UTC, SergejT34 commented on src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetScenarioTask.java
> +        || scenarioNameQueryParameter.firstValue() == "") {
```suggestion
        || scenarioNameQueryParameter.firstValue().equals("")) {

```

2021-12-02 16:41 UTC, merged